# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: push

jobs:
  build:
    name: BUILD alles
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
      options: -w /banaan
      volumes:
        - ${{ github.workspace }}:/banaan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show files
        run: ls
        working-directory: /banaan

      - name: Build in Container
        run: |
          dotnet restore
          dotnet test
          dotnet publish -o out
        working-directory: /banaan
      - name: Pub
        uses: actions/upload-artifact@v4
        with:
          name: martijntje
          path: /banaan/out/

  second:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: En downloaden maar
        uses: actions/download-artifact@v4
        with:
          name: martijntje
      - name: Show content
        run: ls -R







